version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     container_name: wp_boilerplate
     image: wordpress:latest
     ports:
      - "80:80"
      - "443:443"
     links:
      - db
     volumes:
       - ./:/code
       - ./wp-src:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: admin
       WORDPRESS_DB_NAME: wordpress

   db:
     image: mysql:5.7
     ports:
      - "3306"
     container_name: wp_boilerplate-mysql
     volumes:
       - db_data:/var/lib/mysql
       - ./devdb:/devdb
       - ./makeDB.sh:/makeDB.sh
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
volumes:
    db_data: {}